# This is a basic workflow to help you get started with Actions

name: Template CI

# Controls when the action will run. 
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          registry: jfrog.local:8081
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_TOKEN }}
      
      - name: Calculate Prefix
        id: prefix
        run: echo "##[set-output name=prefix;]$(if [ ${GITHUB_REF##*/} == "master" ]; then echo ''; else echo '${GITHUB_REF##*/}-'; fi)"
      
      - name: Bump version and push tag
        uses: hennejg/github-tag-action@v4.2.4
        id: semantic
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          tag_prefix: ${{ steps.prefix.outputs.prefix  }}
        
      - name: Do something when a new release published
        run: |
          echo ${{ steps.semantic.outputs.new_tag }}