# This is a basic workflow to help you get started with Actions

name: Cleanup

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 */12 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  clean-workers:
    runs-on: ${{ matrix.workers }}
    strategy:
      matrix:
        workers: [worker1, worker2]
    # The type of runner that the job will run on

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: docker system prune --all --force
